Swtich singularity+conda setup to singularity setup for snakemake tasks
uab-cgds-worthey/quac pull request #70
Opened 2023-04-10 10:27 UTC by ManavalanG

# Pull request

This PR refactors snakemake pipeline to run all tasks in singularity env instead of singularity+conda setup (and singularity for few tasks). This will improve reproducibility.

What was done?

1. For conda environments with single tool dependency, biocontainers from quay.io was used.
2. For conda environments with multiple tools dependency, _mulled_ container was created using [biocontainer's multi-package-containers](https://github.com/BioContainers/multi-package-containers/)
3. Rules that used snakemake-wrappers were refactored to remove snakemake-wrapper and instead explicitly define the commands used. This was done as snakemake-wrappers required creation of conda env.

Please fill in the checklist below and comment as needed.

- [x] Was code modified? Briefly describe. _Please see description above._
- [x] Was documentation modified? Briefly describe. _Yes, to reflect the refactoring in this PR._
- [x] Is this a bug-fix? Briefly describe. _No_
- [x] Is this a feature addition? Briefly describe. _It is an enhancement to improve reproducibility._
- [x] Did you modify QuaC-Watch config file? If so, did you modify multiqc template
  `configs/multiqc_config_template.jinja2` and script `src/quac_watch/create_mutliqc_configs.py` as necessary? _Not modified._
- [x] Did you perform system-level testing manually as described in master readme doc? Did it pass completely? If not why? _Yes._
- [ ] Updated `Changelog.md` file with change logs in recommended format?

## Anything else reviewer should know?

No.

2023-04-10 20:58 UTC, wilkb777 requested changes

2023-04-11 04:08 UTC, ManavalanG commented on docs/reqts_configs.md
Good point. I checked to see if there is a similar option to pull all singularity images, but there is not any. Let's just remove the whole section `Create singularity environments for tools used in QuaC pipeline`?

2023-04-12 18:56 UTC, wilkb777 commented on docs/reqts_configs.md
that's a good idea to just remove it all since it's really not necessary now given that there is no equivalent command. One option might be to encourage running the system tests after install as this will download all the containers during that run rather than someone unknowingly trying to run multiple instances of QuaC at the same time and each one tries downloading images potentially causing issues.

2023-04-14 04:51 UTC, ManavalanG commented on docs/reqts_configs.md
Done :)

2023-04-18 18:30 UTC, wilkb777 commented on docs/reqts_configs.md
LGTM

2023-04-18 19:07 UTC, merged